- (base) root@esa-adb-gpu:~/Master_Thesis# conda create -n flam_env python=3.10 -y
- conda activate flam_env
- git clone https://github.com/owkin/FLamby.git
- cd FLamby
- make enable=fed_tcga_brca install # This installs FLamby plus only the dependencies for Fed-TCGA-BRCA.

In [4]:
import sys
print(sys.executable)
print(sys.path)

/Users/nataliamorenoblasco/anaconda3/envs/flam_env/bin/python
['/Users/nataliamorenoblasco/Desktop/Master_Thesis', '/Users/nataliamorenoblasco/anaconda3/envs/flam_env/lib/python310.zip', '/Users/nataliamorenoblasco/anaconda3/envs/flam_env/lib/python3.10', '/Users/nataliamorenoblasco/anaconda3/envs/flam_env/lib/python3.10/lib-dynload', '', '/Users/nataliamorenoblasco/anaconda3/envs/flam_env/lib/python3.10/site-packages']

In [2]:
import sys
print(sys.executable)

/root/miniconda3/envs/flamby/bin/python

In [1]:
import lifelines
print("Lifelines OK ✅")

Lifelines OK ✅

In [1]:
!which python

/root/miniconda3/envs/flamby/bin/python

# Start here:

In [2]:
from flamby.datasets.fed_tcga_brca import FedTcgaBrca

In [3]:
# Example: load training data for center 0
center0_train = FedTcgaBrca(center=0, train=True, pooled=False)

print("Center 0 - Training samples:", len(center0_train))

# Inspect one sample
X, y = center0_train[0]
print("Features shape:", X.shape)
print("Label:", y)

Center 0 - Training samples: 248
Features shape: torch.Size([39])
Label: tensor([  1., 921.])

/Users/nataliamorenoblasco/Desktop/Master_Thesis/FLamby/flamby/datasets/fed_tcga_brca/dataset.py:51: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return (torch.tensor(x, dtype=self.X_dtype), torch.tensor(y, dtype=self.y_dtype))

### Read data from center 0: with no features

In [ ]:
import pandas as pd
import torch
from flamby.datasets.fed_tcga_brca import FedTcgaBrca

# Load training set for center 0
center0_train = FedTcgaBrca(center=0, train=True) 

"""
train=True → loads the training split of Center 0

train=False → loads the test split of Center 0

pooled=True → ignores centers and merges everything into one pooled dataset (train or test depending on the flag)
"""

# Convert to DataFrame
features_list = []
labels_list = []

for X, y in center0_train:
    features_list.append(X.numpy())
    labels_list.append(y.numpy())

df_features = pd.DataFrame(features_list)
df_labels = pd.DataFrame(labels_list, columns=["event", "time"])

# Combine features + labels
df_center0 = pd.concat([df_features, df_labels], axis=1)

# Show all rows/columns (careful, it may be big)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

# Rename columns to something clearer
df_center0.columns = [f"feature_{i}" for i in range(39)] + ["event", "time"]
df_center0.head()  # or df_center0 to print everything

/root/Master_Thesis/FLamby/flamby/datasets/fed_tcga_brca/dataset.py:51: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return (torch.tensor(x, dtype=self.X_dtype), torch.tensor(y, dtype=self.y_dtype))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,event,time
0,60.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,921.0
1,43.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1325.0
2,89.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1545.0
3,50.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1142.0
4,63.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2329.0

### Read data from center 0: with features (brom brca.csv)

In [4]:
import pandas as pd
import torch
from flamby.datasets.fed_tcga_brca import FedTcgaBrca
import os

# Load training set for center 0
center0_train = FedTcgaBrca(center=0, train=True)

# --- STEP 1: Get feature names from the original CSV ---
# (You can adapt this path if needed)
csv_path = os.path.join(
    os.path.dirname(__import__('flamby').__file__),
    "datasets/fed_tcga_brca/brca.csv"
)
df_full = pd.read_csv(csv_path)

# The first column is "pid", features are columns 1:40, labels are columns 40:42
feature_names = df_full.columns[1:40].tolist()
label_names = df_full.columns[40:42].tolist()  # ["E", "T"]

# --- STEP 2: Build DataFrame from dataset tensors ---
features_list = []
labels_list = []

for X, y in center0_train:
    features_list.append(X.numpy())
    labels_list.append(y.numpy())

df_features = pd.DataFrame(features_list, columns=feature_names)
df_labels = pd.DataFrame(labels_list, columns=label_names)

# --- STEP 3: Combine features + labels ---
df_center0 = pd.concat([df_features, df_labels], axis=1)

# Optional: view all columns
pd.set_option("display.max_columns", None)

print(df_center0.head())

   age_at_index  ethnicity_not hispanic or latino  ethnicity_not reported  \
0          60.0                               0.0                     1.0
1          43.0                               1.0                     0.0
2          89.0                               1.0                     0.0
3          50.0                               1.0                     0.0
4          63.0                               0.0                     0.0

   race_asian  race_black or african american  race_not reported  race_white  \
0         0.0                             0.0                0.0         1.0
1         0.0                             0.0                0.0         1.0
2         0.0                             1.0                0.0         0.0
3         0.0                             0.0                0.0         1.0
4         0.0                             0.0                0.0         1.0

   ajcc_pathologic_m_MX  ajcc_pathologic_n_N0 (i-)  ajcc_pathologic_n_N1  \
0                   0.0                        0.0                   0.0
1                   0.0                        0.0                   0.0
2                   0.0                        0.0                   0.0
3                   0.0                        0.0                   1.0
4                   0.0                        0.0                   0.0

   ajcc_pathologic_n_N1a  ajcc_pathologic_n_N2  ajcc_pathologic_n_N2a  \
0                    0.0                   0.0                    0.0
1                    0.0                   0.0                    0.0
2                    0.0                   0.0                    0.0
3                    0.0                   0.0                    0.0
4                    1.0                   0.0                    0.0

   ajcc_pathologic_stage_Stage IA  ajcc_pathologic_stage_Stage IIA  \
0                             0.0                              0.0
1                             0.0                              0.0
2                             0.0                              0.0
3                             0.0                              1.0
4                             0.0                              0.0

   ajcc_pathologic_stage_Stage IIB  ajcc_pathologic_stage_Stage IIIA  \
0                              0.0                               0.0
1                              0.0                               0.0
2                              0.0                               0.0
3                              0.0                               0.0
4                              1.0                               0.0

   ajcc_pathologic_stage_Stage IIIC  ajcc_pathologic_t_T1c  \
0                               0.0                    0.0
1                               1.0                    0.0
2                               0.0                    1.0
3                               0.0                    0.0
4                               0.0                    0.0

   ajcc_pathologic_t_T2  ajcc_pathologic_t_T3  \
0                   0.0                   0.0
1                   1.0                   0.0
2                   0.0                   0.0
3                   0.0                   0.0
4                   1.0                   0.0

   ajcc_staging_system_edition_5th  ajcc_staging_system_edition_6th  \
0                              0.0                              1.0
1                              0.0                              0.0
2                              0.0                              0.0
3                              0.0                              0.0
4                              0.0                              1.0

   ajcc_staging_system_edition_7th  icd_10_code_C50.9  morphology_8500/3  \
0                              0.0                0.0                1.0
1                              1.0                1.0                0.0
2                              1.0                1.0                1.0
3                              0.0                1.0                1.0
4                              0.0                1.0                1.0

   morphology_8520/3  primary_diagnosis_Infiltrating duct carcinoma, NOS  \
0                0.0                                                1.0
1                1.0                                                0.0
2                0.0                                                1.0
3                0.0                                                1.0
4                0.0                                                1.0

   primary_diagnosis_Lobular carcinoma, NOS  prior_malignancy_yes  \
0                                       0.0                   0.0
1                                       1.0                   0.0
2                                       0.0                   1.0
3                                       0.0                   0.0
4                                       0.0                   0.0

   synchronous_malignancy_Not Reported  treatment_or_therapy_not reported  \
0                                  0.0                                1.0
1                                  0.0                                0.0
2                                  1.0                                0.0
3                                  0.0                                1.0
4                                  0.0                                0.0

   treatment_or_therapy_yes  tumor_stage_stage i  tumor_stage_stage ia  \
0                       0.0                  1.0                   0.0
1                       1.0                  0.0                   0.0
2                       1.0                  1.0                   0.0
3                       0.0                  0.0                   0.0
4                       1.0                  0.0                   0.0

   tumor_stage_stage iia  tumor_stage_stage iib  tumor_stage_stage iiia  \
0                    0.0                    0.0                     0.0
1                    0.0                    0.0                     0.0
2                    0.0                    0.0                     0.0
3                    1.0                    0.0                     0.0
4                    0.0                    1.0                     0.0

   tumor_stage_stage iiic    E       T
0                     0.0  1.0   921.0
1                     1.0  0.0  1325.0
2                     0.0  0.0  1545.0
3                     0.0  1.0  1142.0
4                     0.0  0.0  2329.0

/Users/nataliamorenoblasco/Desktop/Master_Thesis/FLamby/flamby/datasets/fed_tcga_brca/dataset.py:51: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return (torch.tensor(x, dtype=self.X_dtype), torch.tensor(y, dtype=self.y_dtype))

In [15]:
import pandas as pd
import torch
from flamby.datasets.fed_tcga_brca import FedTcgaBrca

# Load training set for center 0
center1_train = FedTcgaBrca(center=1, train=True) 

# Convert to DataFrame
features_list = []
labels_list = []

for X, y in center1_train:
    features_list.append(X.numpy())
    labels_list.append(y.numpy())

df_features = pd.DataFrame(features_list)
df_labels = pd.DataFrame(labels_list, columns=["event", "time"])

# Combine features + labels
df_center1 = pd.concat([df_features, df_labels], axis=1)

# Show all rows/columns (careful, it may be big)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

# Rename columns to something clearer
df_center1.columns = [f"feature_{i}" for i in range(39)] + ["event", "time"]
df_center1.head()  # or df_center0 to print everything

/root/Master_Thesis/FLamby/flamby/datasets/fed_tcga_brca/dataset.py:51: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return (torch.tensor(x, dtype=self.X_dtype), torch.tensor(y, dtype=self.y_dtype))

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,event,time
0,63.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,343.0
1,41.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1604.0
2,49.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2108.0
3,61.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2097.0
4,68.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3088.0

In [9]:
from flamby.datasets.fed_tcga_brca import TcgaBrcaRaw, FedTcgaBrca

# Raw dataset
mydataset_raw = TcgaBrcaRaw()

# Pooled test dataset
mydataset_pooled = FedTcgaBrca(train=False, pooled=True)

# Center 2 train dataset
mydataset_local2= FedTcgaBrca(center=2, train=True, pooled=False)

# Computing the length of mydataset_local2
N = len(mydataset_local2)

# Accessing individual samples
X, y = mydataset_local2[N // 2]

/root/Master_Thesis/FLamby/flamby/datasets/fed_tcga_brca/dataset.py:51: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return (torch.tensor(x, dtype=self.X_dtype), torch.tensor(y, dtype=self.y_dtype))

In [10]:
from flamby.datasets.fed_tcga_brca import TcgaBrcaRaw

raw_dataset = TcgaBrcaRaw()
print("Raw samples:", len(raw_dataset))

Raw samples: 1096

In [12]:
import pandas as pd

features_list = []
labels_list = []

for X, y in raw_dataset:
    features_list.append(X.numpy())
    labels_list.append(y.numpy())

df_features = pd.DataFrame(features_list)
df_labels = pd.DataFrame(labels_list, columns=["event", "time"])

df_raw = pd.concat([df_features, df_labels], axis=1)

# Show nicely in Jupyter
df_raw.head()   # or just df_raw

/root/Master_Thesis/FLamby/flamby/datasets/fed_tcga_brca/dataset.py:51: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return (torch.tensor(x, dtype=self.X_dtype), torch.tensor(y, dtype=self.y_dtype))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,event,time
0,90.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,538.0
1,90.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,677.0
2,90.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,174.0
3,55.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2072.0
4,52.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,678.0